### ISSUE TITLE
AttributeError: 'module' object has no attribute 'MolFromFASTA'

### ISSUE THREAD

**Issue by ghost** [EBjerrum/pICalculax#1]
Hi, I'm trying to use this tool but I'm getting an error message, is there anything I'm missing ? 

I installed rdkit from bash, 
 sudo apt-get install python-rdkit librdkit1 rdkit-data

and I tried: 
 python pICalculax.py --fasta ICECREAM FATCAT

that gives me 
AttributeError: 'module' object has no attribute 'MolFromFASTA'

**Comment by EBjerrum** [comment]
Sorry, first saw you issue now. What version of RDKit are you using? Newer versions have the Chem.MolFromFASTA function.
